import {
  Activity,
  CDSDocument,
  LearningResource,
  LocalGovernment,
  Member,
  MonthlyReport,
  Task,
} from '../types';

export const INITIAL_LGS: LocalGovernment[] = [
  {
    id: 'lg-akure',
    name: 'Akure South LG',
    state: 'Ondo State',
    presidentId: 'user-lg-pres',
    presidentName: 'Olumide Williams',
    meetingVenue: 'Akure South Local Government Hall, Akure',
    meetingDay: 'Every Thursday, 10:00 AM',
    activeMemberCount: 42,
  },
  {
    id: 'lg-ondo',
    name: 'Ondo West LG',
    state: 'Ondo State',
    presidentId: 'user-surulere-pres',
    presidentName: 'Kemi Balogun',
    meetingVenue: 'Ondo West Youth Centre, Ondo City',
    meetingDay: 'Every Thursday, 10:00 AM',
    activeMemberCount: 38,
  },
  {
    id: 'lg-owo',
    name: 'Owo LG',
    state: 'Ondo State',
    presidentId: 'user-island-pres',
    presidentName: 'Tariq Sanusi',
    meetingVenue: 'Owo Local Government Secretariat',
    meetingDay: 'Every Thursday, 11:00 AM',
    activeMemberCount: 29,
  },
  {
    id: 'lg-ore',
    name: 'Odigbo LG (Ore)',
    state: 'Ondo State',
    presidentId: 'user-alimosho-pres',
    presidentName: 'Chioma Nnamdi',
    meetingVenue: 'Odigbo Secretariat Complex, Ore',
    meetingDay: 'Every Thursday, 9:30 AM',
    activeMemberCount: 56,
  },
  {
    id: 'lg-ikare',
    name: 'Akoko North-East LG (Ikare)',
    state: 'Ondo State',
    presidentId: 'user-kosofe-pres',
    presidentName: 'Yusuf Danjuma',
    meetingVenue: 'Ikare Local Government Hall',
    meetingDay: 'Every Thursday, 10:00 AM',
    activeMemberCount: 31,
  },
];

export const INITIAL_MEMBERS: Member[] = [
  {
    id: 'user-coordinator',
    fullName: 'Dr. Adebayo Ogunlesi',
    email: 'coordinator@dodeel.org',
    phone: '+234 803 111 2233',
    lgId: 'lg-akure',
    lgName: 'Ondo State NYSC Directorate (Akure)',
    state: 'Ondo State',
    role: 'CDS_COORDINATOR',
    membershipStatus: 'ACTIVE',
    dateJoined: '2025-01-15',
    profilePhoto: '/src/assets/images/avatar_coordinator_male_1791075663076.jpg',
    skills: ['Strategic Governance', 'Programme Leadership', 'Public Policy'],
    bio: 'State CDS Coordinator overseeing DO-DEEL CDS initiatives across all Local Government Areas in Ondo State.',
    assignedTeam: 'State Advisory Board',
    password: 'password123',
  },
  {
    id: 'user-state-pres',
    fullName: 'Chidinma Eze',
    email: 'statepresident@dodeel.org',
    phone: '+234 802 345 6789',
    lgId: 'lg-akure',
    lgName: 'State Secretariat',
    state: 'Ondo State',
    role: 'STATE_PRESIDENT',
    membershipStatus: 'ACTIVE',
    dateJoined: '2025-02-01',
    profilePhoto: '/src/assets/images/avatar_president_female_1791075674697.jpg',
    skills: ['Operations Management', 'Public Speaking', 'Partnership Development'],
    callUpNo: 'NYSC/OND/2026/089412',
    stateCode: 'OD/26A/0912',
    bio: 'State President directing operational synergy, capacity building, and digital literacy outreach in Ondo.',
    assignedTeam: 'State Executive Council',
    password: 'password123',
    fcmbAccount: '0123456789',
    ppaName: 'Ondo State NYSC Headquarters',
    ppaAddress: 'State Secretariat, Akure, Ondo State',
  },
  {
    id: 'user-vp-growth',
    fullName: 'Babatunde Adeleke',
    email: 'vpgrowth@dodeel.org',
    phone: '+234 814 567 8901',
    lgId: 'lg-akure',
    lgName: 'State Secretariat',
    state: 'Ondo State',
    role: 'VP_GROWTH',
    membershipStatus: 'ACTIVE',
    dateJoined: '2025-02-10',
    profilePhoto: '/src/assets/images/avatar_growth_male_1791075686041.jpg',
    skills: ['Digital Marketing', 'Community Engagement', 'Social Media Strategy'],
    callUpNo: 'NYSC/OND/2026/102941',
    stateCode: 'OD/26A/1402',
    bio: 'Leading statewide visibility campaigns, campus outreach, and online growth metrics.',
    assignedTeam: 'Growth & Visibility',
    password: 'password123',
  },
  {
    id: 'user-vp-accountability',
    fullName: 'Fatima Aliyu',
    email: 'vpaccountability@dodeel.org',
    phone: '+234 809 876 5432',
    lgId: 'lg-akure',
    lgName: 'State Secretariat',
    state: 'Ondo State',
    role: 'VP_ACCOUNTABILITY',
    membershipStatus: 'ACTIVE',
    dateJoined: '2025-02-10',
    profilePhoto: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    skills: ['KPI Tracking', 'Auditing', 'Performance Analytics'],
    callUpNo: 'NYSC/OND/2026/119284',
    stateCode: 'OD/26A/1884',
    bio: 'Enforcing execution rigour, monitoring deadlines, and ensuring timely evidence submission.',
    assignedTeam: 'Accountability & Compliance',
    password: 'password123',
  },
  {
    id: 'user-vp-impact',
    fullName: 'Emeka Okonkwo',
    email: 'vpimpact@dodeel.org',
    phone: '+234 805 432 1098',
    lgId: 'lg-ondo',
    lgName: 'State Secretariat',
    state: 'Ondo State',
    role: 'VP_COMMUNITY_IMPACT',
    membershipStatus: 'ACTIVE',
    dateJoined: '2025-02-10',
    profilePhoto: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    skills: ['Community Outreach', 'Impact Assessment', 'Beneficiary Research'],
    callUpNo: 'NYSC/OND/2026/120931',
    stateCode: 'OD/26A/2105',
    bio: 'Coordinating high-impact grassroots digital literacy training and measuring beneficiary outcomes.',
    assignedTeam: 'Community Impact & Outreach',
    password: 'password123',
  },
  {
    id: 'user-lg-pres',
    fullName: 'Olumide Williams',
    email: 'ikejapresident@dodeel.org',
    phone: '+234 812 345 6701',
    lgId: 'lg-akure',
    lgName: 'Akure South LG',
    state: 'Ondo State',
    role: 'LG_PRESIDENT',
    membershipStatus: 'ACTIVE',
    dateJoined: '2025-02-15',
    profilePhoto: '/src/assets/images/avatar_lg_female_1791075698436.jpg',
    skills: ['Grassroots Leadership', 'Logistics', 'Event Coordination'],
    callUpNo: 'NYSC/OND/2026/133092',
    stateCode: 'OD/26A/3012',
    bio: 'Overseeing Akure South LG weekly CDS operations, mentoring programmes, and school computer training.',
    assignedTeam: 'Akure South LG Executive Committee',
    password: 'password123',
  },
  {
    id: 'user-exec-training',
    fullName: 'Amina Bello',
    email: 'amina.bello@dodeel.org',
    phone: '+234 808 765 4321',
    lgId: 'lg-akure',
    lgName: 'Akure South LG',
    state: 'Ondo State',
    role: 'EXECUTIVE',
    membershipStatus: 'ACTIVE',
    dateJoined: '2025-02-20',
    profilePhoto: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80',
    skills: ['Python', 'Web Development', 'Digital Literacy Mentoring'],
    callUpNo: 'NYSC/OND/2026/144901',
    stateCode: 'OD/26A/3421',
    bio: 'Training & Curriculum Lead for Akure South LG secondary school digital adoption programmes.',
    assignedTeam: 'Training & Curriculum',
    password: 'password123',
  },
  {
    id: 'user-group-leader',
    fullName: 'Samuel Uche',
    email: 'samuel.uche@dodeel.org',
    phone: '+234 813 987 6543',
    lgId: 'lg-akure',
    lgName: 'Akure South LG',
    state: 'Ondo State',
    role: 'GROUP_LEADER',
    membershipStatus: 'ACTIVE',
    dateJoined: '2025-03-01',
    profilePhoto: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    skills: ['UI/UX Design', 'Mentorship', 'Field Logistics'],
    callUpNo: 'NYSC/OND/2026/155023',
    stateCode: 'OD/26A/3980',
    bio: 'Team Alpha Leader coordinating student workshops at Agidingbi Junior Grammar School.',
    assignedTeam: 'School Outreach Team Alpha',
    password: 'password123',
  },
  {
    id: 'user-member-1',
    fullName: 'Blessing Johnson',
    email: 'blessing.johnson@dodeel.org',
    phone: '+234 816 112 2334',
    lgId: 'lg-akure',
    lgName: 'Akure South LG',
    state: 'Ondo State',
    role: 'MEMBER',
    membershipStatus: 'ACTIVE',
    dateJoined: '2025-03-10',
    profilePhoto: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    skills: ['Content Writing', 'Canva Graphics', 'Social Media'],
    callUpNo: 'NYSC/OND/2026/166722',
    stateCode: 'OD/26A/4211',
    bio: 'Corps member enthusiastic about empowering girls with computer and internet literacy.',
    assignedTeam: 'School Outreach Team Alpha',
    password: 'password123',
    fcmbAccount: '9876543210',
    ppaName: 'Agidingbi Junior Grammar School',
    ppaAddress: '12, Agidingbi Road, Ikeja, Lagos (Relocated to Akure)',
    requiresProfileUpdate: true,
  },
  {
    id: 'user-member-2',
    fullName: 'Tunde Bakare',
    email: 'tunde.bakare@dodeel.org',
    phone: '+234 802 998 8776',
    lgId: 'lg-akure',
    lgName: 'Akure South LG',
    state: 'Ondo State',
    role: 'MEMBER',
    membershipStatus: 'ACTIVE',
    dateJoined: '2025-03-12',
    skills: ['Data Entry', 'Excel', 'Hardware Troubleshooting'],
    callUpNo: 'NYSC/OND/2026/177890',
    stateCode: 'OD/26A/4560',
    assignedTeam: 'School Outreach Team Alpha',
    password: 'password123',
    requiresProfileUpdate: true,
  },
  {
    id: 'user-member-3',
    fullName: 'Grace Okafor',
    email: 'grace.okafor@dodeel.org',
    phone: '+234 810 554 4332',
    lgId: 'lg-ondo',
    lgName: 'Ondo West LG',
    state: 'Ondo State',
    role: 'MEMBER',
    membershipStatus: 'ACTIVE',
    dateJoined: '2025-03-15',
    skills: ['Public Speaking', 'Project Management'],
    callUpNo: 'NYSC/OND/2026/188902',
    stateCode: 'OD/26A/5012',
    assignedTeam: 'Outreach & Mentorship',
    password: 'password123',
    requiresProfileUpdate: true,
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-1',
    title: 'Conduct Secondary School Digital Literacy Workshop (Phase 1)',
    description: 'Deliver hands-on training covering Google Docs, basic spreadsheet budgeting, and safe internet browsing for 60 students at Agidingbi Grammar School.',
    assignedTo: 'user-exec-training',
    assignedToName: 'Amina Bello',
    assignedToRole: 'EXECUTIVE',
    assignedUserId: 'user-exec-training',
    assignedUserName: 'Amina Bello',
    assignedUserRole: 'EXECUTIVE',
    assignedBy: 'user-lg-pres',
    assignedByName: 'Olumide Williams',
    assignedLG: 'lg-akure',
    assignedLGName: 'Akure South LG',
    lgId: 'lg-akure',
    lgName: 'Akure South LG',
    team: 'Training & Curriculum',
    kpi: '60 students trained with verified attendance and feedback forms submitted.',
    priority: 'HIGH',
    startDate: '2026-09-20',
    deadline: '2026-10-01',
    manualProgress: 'COMPLETED',
    hasEvidence: true,
    evidence: {
      type: 'URL',
      url: 'https://drive.google.com/drive/folders/dodeel-ikeja-agidingbi-photos',
      description: 'Photos, student attendance sign-in sheet, and video recap of the session.',
      submittedAt: '2026-10-01T15:30:00Z',
      submittedBy: 'user-exec-training',
      submittedByName: 'Amina Bello',
    },
    comments: [
      {
        id: 'comm-1',
        authorId: 'user-lg-pres',
        authorName: 'Olumide Williams',
        authorRole: 'LG_PRESIDENT',
        text: 'Excellent turnout! Principal commended DO-DEEL corps members.',
        createdAt: '2026-10-01T17:00:00Z',
      },
    ],
    completionDate: '2026-10-01',
    completedAt: '2026-10-01',
    result: 'Successfully trained 64 junior secondary students with 94% comprehension score on the exit quiz.',
    createdBy: 'user-lg-pres',
    createdByName: 'Olumide Williams',
    createdAt: '2026-09-18T09:00:00Z',
    updatedAt: '2026-10-01T15:30:00Z',
  },
  {
    id: 'task-2',
    title: 'Recruit 20 New NYSC Corps Members to DO-DEEL CDS',
    description: 'Coordinate membership mobilization drive across LG orientation desks and share onboarding registration link.',
    assignedTo: 'user-vp-growth',
    assignedToName: 'Babatunde Adeleke',
    assignedToRole: 'VP_GROWTH',
    assignedUserId: 'user-vp-growth',
    assignedUserName: 'Babatunde Adeleke',
    assignedUserRole: 'VP_GROWTH',
    assignedBy: 'user-state-pres',
    assignedByName: 'Chidinma Eze',
    assignedLG: 'lg-akure',
    assignedLGName: 'State Secretariat',
    lgId: 'lg-akure',
    lgName: 'State Secretariat',
    team: 'Growth & Visibility',
    kpi: 'At least 20 active corps members registered on the portal.',
    priority: 'HIGH',
    startDate: '2026-09-25',
    deadline: '2026-10-05',
    manualProgress: 'IN_PROGRESS',
    hasEvidence: false,
    comments: [
      {
        id: 'comm-2',
        authorId: 'user-state-pres',
        authorName: 'Chidinma Eze',
        authorRole: 'STATE_PRESIDENT',
        text: 'Please also liaise with the Surulere and Odigbo LG (Ore) desks.',
        createdAt: '2026-09-28T11:00:00Z',
      },
    ],
    createdBy: 'user-state-pres',
    createdByName: 'Chidinma Eze',
    createdAt: '2026-09-24T10:00:00Z',
    updatedAt: '2026-09-28T11:00:00Z',
  },
  {
    id: 'task-3',
    title: 'Collate & Verify Q3 LG Task Reports & Evidence',
    description: 'Audit task completion across all 5 active Local Governments, flag missing evidence links, and prepare accountability briefing.',
    assignedTo: 'user-vp-accountability',
    assignedToName: 'Fatima Aliyu',
    assignedToRole: 'VP_ACCOUNTABILITY',
    assignedUserId: 'user-vp-accountability',
    assignedUserName: 'Fatima Aliyu',
    assignedUserRole: 'VP_ACCOUNTABILITY',
    assignedBy: 'user-coordinator',
    assignedByName: 'Dr. Adebayo Ogunlesi',
    assignedLG: 'lg-akure',
    assignedLGName: 'State Secretariat',
    lgId: 'lg-akure',
    lgName: 'State Secretariat',
    team: 'Accountability & Compliance',
    kpi: 'Complete accountability matrix submitted to State Coordinator.',
    priority: 'HIGH',
    startDate: '2026-09-15',
    deadline: '2026-09-28', // Past deadline without completion -> will be OVERDUE!
    manualProgress: 'IN_PROGRESS',
    hasEvidence: false,
    comments: [
      {
        id: 'comm-3',
        authorId: 'user-coordinator',
        authorName: 'Dr. Adebayo Ogunlesi',
        authorRole: 'CDS_COORDINATOR',
        text: 'This briefing is required for the NYSC State Directorate meeting.',
        createdAt: '2026-09-29T08:00:00Z',
      },
    ],
    createdBy: 'user-coordinator',
    createdByName: 'Dr. Adebayo Ogunlesi',
    createdAt: '2026-09-14T10:00:00Z',
    updatedAt: '2026-09-29T08:00:00Z',
  },
  {
    id: 'task-4',
    title: 'Publish 3 Social Media Carousels on In-Demand Digital Skills',
    description: 'Create and post carousel graphics for Instagram and LinkedIn highlighting Python, UI/UX, and Data Analysis pathways for Nigerian graduates.',
    assignedTo: 'user-member-1',
    assignedToName: 'Blessing Johnson',
    assignedToRole: 'MEMBER',
    assignedUserId: 'user-member-1',
    assignedUserName: 'Blessing Johnson',
    assignedUserRole: 'MEMBER',
    assignedBy: 'user-vp-growth',
    assignedByName: 'Babatunde Adeleke',
    assignedLG: 'lg-akure',
    assignedLGName: 'Akure South LG',
    lgId: 'lg-akure',
    lgName: 'Akure South LG',
    team: 'Growth & Visibility',
    kpi: '3 carousels published with DO-DEEL branding and over 300 impressions.',
    priority: 'MEDIUM',
    startDate: '2026-10-02',
    deadline: '2026-10-10',
    manualProgress: 'IN_PROGRESS',
    hasEvidence: false,
    comments: [],
    createdBy: 'user-vp-growth',
    createdByName: 'Babatunde Adeleke',
    createdAt: '2026-10-01T14:00:00Z',
    updatedAt: '2026-10-02T10:00:00Z',
  },
  {
    id: 'task-5',
    title: 'Mobilize 50 Local Artisans for Smartphone Accounting Workshop',
    description: 'Liaise with Ikeja Market Association to register 50 tailors, carpenters, and shopkeepers for free cashflow bookkeeping app training.',
    assignedTo: 'user-group-leader',
    assignedToName: 'Samuel Uche',
    assignedToRole: 'GROUP_LEADER',
    assignedUserId: 'user-group-leader',
    assignedUserName: 'Samuel Uche',
    assignedUserRole: 'GROUP_LEADER',
    assignedBy: 'user-lg-pres',
    assignedByName: 'Olumide Williams',
    assignedLG: 'lg-akure',
    assignedLGName: 'Akure South LG',
    lgId: 'lg-akure',
    lgName: 'Akure South LG',
    team: 'Community Impact & Outreach',
    kpi: '50 confirmed artisan signups with venue and phone numbers documented.',
    priority: 'HIGH',
    startDate: '2026-10-04',
    deadline: '2026-10-14',
    manualProgress: 'NOT_STARTED',
    hasEvidence: false,
    comments: [],
    createdBy: 'user-lg-pres',
    createdByName: 'Olumide Williams',
    createdAt: '2026-10-02T16:00:00Z',
    updatedAt: '2026-10-02T16:00:00Z',
  },
  {
    id: 'task-6',
    title: 'Surulere Youth Digital Skills Clinic & CV Review',
    description: 'Host interactive session for 45 corps members and local job seekers on crafting ATS-compliant resumes and online portfolio creation.',
    assignedTo: 'user-vp-impact',
    assignedToName: 'Emeka Okonkwo',
    assignedToRole: 'VP_COMMUNITY_IMPACT',
    assignedUserId: 'user-vp-impact',
    assignedUserName: 'Emeka Okonkwo',
    assignedUserRole: 'VP_COMMUNITY_IMPACT',
    assignedBy: 'user-coordinator',
    assignedByName: 'Dr. Adebayo Ogunlesi',
    assignedLG: 'lg-ondo',
    assignedLGName: 'Ondo West LG',
    lgId: 'lg-ondo',
    lgName: 'Ondo West LG',
    team: 'Community Impact & Outreach',
    kpi: '40 CVs optimized and verified with mentor sign-off.',
    priority: 'HIGH',
    startDate: '2026-09-22',
    deadline: '2026-09-30',
    manualProgress: 'COMPLETED',
    hasEvidence: true,
    evidence: {
      type: 'URL',
      url: 'https://drive.google.com/drive/folders/dodeel-surulere-cv-clinic',
      description: 'Photos, attendance register, and 42 reviewed CV samples.',
      submittedAt: '2026-09-30T16:00:00Z',
      submittedBy: 'user-vp-impact',
      submittedByName: 'Emeka Okonkwo',
    },
    completionDate: '2026-09-30',
    completedAt: '2026-09-30T16:00:00Z',
    result: '45 attendees mentored; 42 resumes upgraded with 100% positive participant feedback.',
    comments: [
      {
        id: 'comm-6',
        authorId: 'user-coordinator',
        authorName: 'Dr. Adebayo Ogunlesi',
        authorRole: 'CDS_COORDINATOR',
        text: 'Great initiative. Let us replicate in Alimosho next month.',
        createdAt: '2026-10-01T09:00:00Z',
      },
    ],
    createdBy: 'user-coordinator',
    createdByName: 'Dr. Adebayo Ogunlesi',
    createdAt: '2026-09-20T10:00:00Z',
    updatedAt: '2026-09-30T16:00:00Z',
  },
  {
    id: 'task-7',
    title: 'Surulere Secondary Schools Computer Lab Inspection & Audit',
    description: 'Visit 3 public secondary schools in Surulere to inspect working computer terminals and assess readiness for DO-DEEL coding clubs.',
    assignedTo: 'user-member-3',
    assignedToName: 'Grace Okafor',
    assignedToRole: 'MEMBER',
    assignedUserId: 'user-member-3',
    assignedUserName: 'Grace Okafor',
    assignedUserRole: 'MEMBER',
    assignedBy: 'user-vp-impact',
    assignedByName: 'Emeka Okonkwo',
    assignedLG: 'lg-ondo',
    assignedLGName: 'Ondo West LG',
    lgId: 'lg-ondo',
    lgName: 'Ondo West LG',
    team: 'Training & Curriculum',
    kpi: 'Audit report on 3 school labs with inventory table submitted.',
    priority: 'HIGH',
    startDate: '2026-09-15',
    deadline: '2026-09-26', // Past deadline -> OVERDUE
    manualProgress: 'IN_PROGRESS',
    hasEvidence: false,
    comments: [
      {
        id: 'comm-7',
        authorId: 'user-vp-impact',
        authorName: 'Emeka Okonkwo',
        authorRole: 'VP_COMMUNITY_IMPACT',
        text: 'Grace, please submit the audit as soon as possible so we can send the formal request to the Ministry.',
        createdAt: '2026-09-28T14:30:00Z',
      },
    ],
    createdBy: 'user-vp-impact',
    createdByName: 'Emeka Okonkwo',
    createdAt: '2026-09-14T09:00:00Z',
    updatedAt: '2026-09-28T14:30:00Z',
  },
  {
    id: 'task-8',
    title: 'Alimosho Digital Literacy Workshop for Market Women',
    description: 'Teach basic mobile money safety, USSD banking protection, and scam awareness to 50 market traders at Ikotun Market.',
    assignedTo: 'user-exec-training',
    assignedToName: 'Amina Bello',
    assignedToRole: 'EXECUTIVE',
    assignedUserId: 'user-exec-training',
    assignedUserName: 'Amina Bello',
    assignedUserRole: 'EXECUTIVE',
    assignedBy: 'user-coordinator',
    assignedByName: 'Dr. Adebayo Ogunlesi',
    assignedLG: 'lg-ore',
    assignedLGName: 'Odigbo LG (Ore)',
    lgId: 'lg-ore',
    lgName: 'Odigbo LG (Ore)',
    team: 'Community Impact & Outreach',
    kpi: '50 traders trained with verified sign-in sheet and pamphlet distribution photos.',
    priority: 'HIGH',
    startDate: '2026-09-20',
    deadline: '2026-10-06',
    manualProgress: 'IN_PROGRESS',
    hasEvidence: true,
    evidence: {
      type: 'IMAGE',
      url: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?w=600&auto=format&fit=crop&q=80',
      description: 'Session photos showing corps members distributing flyer guides to traders.',
      submittedAt: '2026-09-29T12:00:00Z',
      submittedBy: 'user-exec-training',
      submittedByName: 'Amina Bello',
    },
    reopenedAt: '2026-10-02T10:00:00Z',
    reopenedBy: 'user-vp-accountability',
    reopenedByName: 'Fatima Aliyu',
    reopenReason: 'Reopened by VP Accountability: Photos attached lack verified market trader attendance roster with phone numbers.',
    reopenHistory: [
      {
        reopenedAt: '2026-10-02T10:00:00Z',
        reopenedBy: 'user-vp-accountability',
        reopenedByName: 'Fatima Aliyu',
        reason: 'Missing verified attendance register with contact info.',
      },
    ],
    comments: [
      {
        id: 'comm-8a',
        authorId: 'user-vp-accountability',
        authorName: 'Fatima Aliyu',
        authorRole: 'VP_ACCOUNTABILITY',
        text: '🔄 Responsibility Reopened by Fatima Aliyu: "Missing verified attendance register with contact info." (Deadline updated to: 2026-10-06)',
        createdAt: '2026-10-02T10:00:00Z',
      },
    ],
    createdBy: 'user-coordinator',
    createdByName: 'Dr. Adebayo Ogunlesi',
    createdAt: '2026-09-18T11:00:00Z',
    updatedAt: '2026-10-02T10:00:00Z',
  },
  {
    id: 'task-9',
    title: 'Eti-Osa Digital CV & LinkedIn Optimization Bootcamp',
    description: 'Organize career mentorship session for 35 graduating corps members on tech job platforms, portfolio hosting, and remote work search.',
    assignedTo: 'user-vp-growth',
    assignedToName: 'Babatunde Adeleke',
    assignedToRole: 'VP_GROWTH',
    assignedUserId: 'user-vp-growth',
    assignedUserName: 'Babatunde Adeleke',
    assignedUserRole: 'VP_GROWTH',
    assignedBy: 'user-state-pres',
    assignedByName: 'Chidinma Eze',
    assignedLG: 'lg-etiosa',
    assignedLGName: 'Eti-Osa LG',
    lgId: 'lg-etiosa',
    lgName: 'Eti-Osa LG',
    team: 'Training & Curriculum',
    kpi: '35 verified LinkedIn profiles created/updated with DO-DEEL certification banner.',
    priority: 'MEDIUM',
    startDate: '2026-10-03',
    deadline: '2026-10-12',
    manualProgress: 'IN_PROGRESS',
    hasEvidence: false,
    comments: [],
    createdBy: 'user-state-pres',
    createdByName: 'Chidinma Eze',
    createdAt: '2026-10-02T10:00:00Z',
    updatedAt: '2026-10-03T11:00:00Z',
  },
  {
    id: 'task-10',
    title: 'Ikorodu Secondary School Web Development Introduction',
    description: 'Conduct foundational HTML/CSS demo workshop for 40 senior secondary students at Ikorodu High School.',
    assignedTo: 'user-group-leader',
    assignedToName: 'Samuel Uche',
    assignedToRole: 'GROUP_LEADER',
    assignedUserId: 'user-group-leader',
    assignedUserName: 'Samuel Uche',
    assignedUserRole: 'GROUP_LEADER',
    assignedBy: 'user-coordinator',
    assignedByName: 'Dr. Adebayo Ogunlesi',
    assignedLG: 'lg-ikorodu',
    assignedLGName: 'Ikorodu LG',
    lgId: 'lg-ikorodu',
    lgName: 'Ikorodu LG',
    team: 'Training & Curriculum',
    kpi: '40 students built and previewed basic HTML profile web pages.',
    priority: 'HIGH',
    startDate: '2026-09-18',
    deadline: '2026-09-27',
    manualProgress: 'COMPLETED',
    hasEvidence: true,
    evidence: {
      type: 'URL',
      url: 'https://drive.google.com/drive/folders/dodeel-ikorodu-html-workshop',
      description: 'Student HTML project files, classroom photos, and principal endorsement letter.',
      submittedAt: '2026-09-27T17:00:00Z',
      submittedBy: 'user-group-leader',
      submittedByName: 'Samuel Uche',
    },
    completionDate: '2026-09-27',
    completedAt: '2026-09-27T17:00:00Z',
    result: '40 students completed basic personal web pages and were presented certificates of participation.',
    comments: [],
    createdBy: 'user-coordinator',
    createdByName: 'Dr. Adebayo Ogunlesi',
    createdAt: '2026-09-16T14:00:00Z',
    updatedAt: '2026-09-27T17:00:00Z',
  },
];

export const INITIAL_ACTIVITIES: Activity[] = [
  {
    id: 'act-1',
    title: 'Weekly CDS Meeting & Digital Literacy Peer Mentoring',
    description: 'Regular Thursday CDS session featuring breakout group mentoring on CV building, LinkedIn optimization, and upcoming community projects.',
    date: '2026-10-08',
    time: '10:00',
    locationType: 'IN_PERSON',
    location: 'Ikeja Local Government Council Hall, Lagos',
    lgId: 'lg-akure',
    lgName: 'Akure South LG',
    organizerId: 'user-lg-pres',
    organizerName: 'Olumide Williams',
    organizerRole: 'LG_PRESIDENT',
    status: 'UPCOMING',
    expectedAttendance: 45,
    attendanceRecords: [
      {
        memberId: 'user-exec-training',
        memberName: 'Amina Bello',
        status: 'PRESENT',
        markedAt: '2026-10-01T10:30:00Z',
        markedBy: 'user-lg-pres',
      },
      {
        memberId: 'user-group-leader',
        memberName: 'Samuel Uche',
        status: 'PRESENT',
        markedAt: '2026-10-01T10:30:00Z',
        markedBy: 'user-lg-pres',
      },
      {
        memberId: 'user-member-1',
        memberName: 'Blessing Johnson',
        status: 'PRESENT',
        markedAt: '2026-10-01T10:31:00Z',
        markedBy: 'user-lg-pres',
      },
      {
        memberId: 'user-member-2',
        memberName: 'Tunde Bakare',
        status: 'ABSENT',
        markedAt: '2026-10-01T10:32:00Z',
        markedBy: 'user-lg-pres',
      },
    ],
    createdAt: '2026-09-25T12:00:00Z',
  },
  {
    id: 'act-2',
    title: 'DO-DEEL State-Wide Webinar: AI Tools for Modern Employability',
    description: 'Statewide interactive masterclass on utilizing generative AI, workflow automation, and resume tailoring tools.',
    date: '2026-10-12',
    time: '18:00',
    locationType: 'ONLINE',
    location: 'Google Meet (meet.google.com/dodeel-lagos-ai)',
    lgId: 'ALL',
    lgName: 'State-wide (All LGs)',
    organizerId: 'user-state-pres',
    organizerName: 'Chidinma Eze',
    organizerRole: 'STATE_PRESIDENT',
    status: 'UPCOMING',
    expectedAttendance: 180,
    attendanceRecords: [],
    createdAt: '2026-10-01T10:00:00Z',
  },
  {
    id: 'act-3',
    title: 'Ikeja Secondary School Tech Discovery Day',
    description: 'Field outreach introducing high school learners to coding, graphic design, and ethical cyber awareness.',
    date: '2026-09-28',
    time: '09:30',
    locationType: 'IN_PERSON',
    location: 'Agidingbi Senior Grammar School, Ikeja',
    lgId: 'lg-akure',
    lgName: 'Akure South LG',
    organizerId: 'user-lg-pres',
    organizerName: 'Olumide Williams',
    organizerRole: 'LG_PRESIDENT',
    status: 'COMPLETED',
    expectedAttendance: 60,
    attendanceRecords: [
      {
        memberId: 'user-exec-training',
        memberName: 'Amina Bello',
        status: 'PRESENT',
        markedAt: '2026-09-28T09:45:00Z',
        markedBy: 'user-lg-pres',
      },
      {
        memberId: 'user-group-leader',
        memberName: 'Samuel Uche',
        status: 'PRESENT',
        markedAt: '2026-09-28T09:45:00Z',
        markedBy: 'user-lg-pres',
      },
      {
        memberId: 'user-member-1',
        memberName: 'Blessing Johnson',
        status: 'PRESENT',
        markedAt: '2026-09-28T09:46:00Z',
        markedBy: 'user-lg-pres',
      },
      {
        memberId: 'user-member-2',
        memberName: 'Tunde Bakare',
        status: 'PRESENT',
        markedAt: '2026-09-28T09:46:00Z',
        markedBy: 'user-lg-pres',
      },
    ],
    createdAt: '2026-09-15T08:00:00Z',
  },
];

export const INITIAL_DOCUMENTS: CDSDocument[] = [
  {
    id: 'doc-1',
    title: 'DO-DEEL CDS Official Constitution & Code of Conduct',
    description: 'State governance framework, member rights, disciplinary code, and leadership ethics guidelines for NYSC DO-DEEL CDS.',
    category: 'Governance',
    fileUrl: 'https://example.com/docs/dodeel-constitution-2026.pdf',
    fileSize: '1.4 MB',
    fileType: 'PDF',
    uploadDate: '2026-08-15',
    uploadedBy: 'user-coordinator',
    uploadedByName: 'Dr. Adebayo Ogunlesi',
    visibility: 'ALL',
    version: 'v2.4',
  },
  {
    id: 'doc-2',
    title: 'LG Executive Operations & Handover Manual',
    description: 'Detailed SOP for LG Presidents, General Secretaries, and Committee Chairs regarding clearance, meetings, and activity reporting.',
    category: 'Executive Resources',
    fileUrl: 'https://example.com/docs/executive-operations-manual.pdf',
    fileSize: '2.1 MB',
    fileType: 'PDF',
    uploadDate: '2026-08-20',
    uploadedBy: 'user-state-pres',
    uploadedByName: 'Chidinma Eze',
    visibility: 'EXECUTIVES_ONLY',
    version: 'v3.0',
  },
  {
    id: 'doc-3',
    title: 'Digital Literacy 8-Week Facilitator Syllabus',
    description: 'Comprehensive curriculum guide covering Computer Fundamentals, Office Suites, Canva Design, and Internet Safety for youth outreach.',
    category: 'Training Materials',
    fileUrl: 'https://example.com/docs/digital-literacy-curriculum.pdf',
    fileSize: '3.8 MB',
    fileType: 'PDF',
    uploadDate: '2026-09-01',
    uploadedBy: 'user-coordinator',
    uploadedByName: 'Dr. Adebayo Ogunlesi',
    visibility: 'ALL',
    version: 'v1.2',
  },
  {
    id: 'doc-4',
    title: 'Standard Monthly CDS Report Template & Metric Rubric',
    description: 'Official monthly reporting form including activities assigned, evidence submission format, and beneficiary counts.',
    category: 'Reports & Templates',
    fileUrl: 'https://example.com/docs/monthly-report-template.docx',
    fileSize: '450 KB',
    fileType: 'DOCX',
    uploadDate: '2026-09-10',
    uploadedBy: 'user-state-pres',
    uploadedByName: 'Chidinma Eze',
    visibility: 'ALL',
    version: 'v2.1',
  },
  {
    id: 'doc-5',
    title: 'DO-DEEL Brand Kit & Social Media Templates',
    description: 'Approved logo files, color codes (#10B981 emerald, #0F172A slate), presentation slide deck templates, and flyer layouts.',
    category: 'Branding',
    fileUrl: 'https://example.com/docs/dodeel-branding-kit.zip',
    fileSize: '12.5 MB',
    fileType: 'ZIP',
    uploadDate: '2026-09-12',
    uploadedBy: 'user-state-pres',
    uploadedByName: 'Chidinma Eze',
    visibility: 'ALL',
    version: 'v1.0',
  },
];

export const INITIAL_LEARNING: LearningResource[] = [
  {
    id: 'learn-1',
    title: 'Crash Course: Essential Digital Literacy & Productivity Tools',
    description: 'Master keyboard shortcuts, Google Workspace, cloud storage, and email etiquette for competitive corporate environments.',
    type: 'YOUTUBE',
    url: 'https://www.youtube.com/watch?v=k2ZgP8u3Rrg',
    youtubeVideoId: 'k2ZgP8u3Rrg',
    thumbnailUrl: 'https://img.youtube.com/vi/k2ZgP8u3Rrg/hqdefault.jpg',
    category: 'Digital Literacy',
    durationOrPages: '42 mins',
    publishedBy: 'user-vp-growth',
    publisherName: 'Babatunde Adeleke',
    publisherRole: 'VP_GROWTH',
    createdAt: '2026-09-10T11:00:00Z',
  },
  {
    id: 'learn-2',
    title: 'How to Build a High-Converting Resume & Win LinkedIn Jobs',
    description: 'Practical step-by-step masterclass on ATS resume keywords, portfolio links, and cold messaging recruiters in Nigeria and internationally.',
    type: 'YOUTUBE',
    url: 'https://www.youtube.com/watch?v=ttULgtb_J_U',
    youtubeVideoId: 'ttULgtb_J_U',
    thumbnailUrl: 'https://img.youtube.com/vi/ttULgtb_J_U/hqdefault.jpg',
    category: 'Employability',
    durationOrPages: '28 mins',
    publishedBy: 'user-state-pres',
    publisherName: 'Chidinma Eze',
    publisherRole: 'STATE_PRESIDENT',
    createdAt: '2026-09-15T14:30:00Z',
  },
  {
    id: 'learn-3',
    title: 'Digital Entrepreneurship: Launching an Online Freelance Career',
    description: 'Everything you need to know about setting up payment gateways, finding global clients on Upwork, and pitching digital skills.',
    type: 'YOUTUBE',
    url: 'https://www.youtube.com/watch?v=UB1O30fR-EE',
    youtubeVideoId: 'UB1O30fR-EE',
    thumbnailUrl: 'https://img.youtube.com/vi/UB1O30fR-EE/hqdefault.jpg',
    category: 'Entrepreneurship',
    durationOrPages: '35 mins',
    publishedBy: 'user-vp-growth',
    publisherName: 'Babatunde Adeleke',
    publisherRole: 'VP_GROWTH',
    createdAt: '2026-09-20T09:00:00Z',
  },
  {
    id: 'learn-4',
    title: 'Youth Leadership & Team Accountability Guide',
    description: 'Official DO-DEEL leadership handbook on project coordination, effective communication, and monitoring community impact.',
    type: 'PDF',
    url: 'https://example.com/learning/dodeel-leadership-guide.pdf',
    category: 'Leadership',
    durationOrPages: '24 Pages',
    publishedBy: 'user-coordinator',
    publisherName: 'Dr. Adebayo Ogunlesi',
    publisherRole: 'CDS_COORDINATOR',
    createdAt: '2026-09-22T10:00:00Z',
  },
  {
    id: 'learn-5',
    title: 'Intro to Web Development & HTML/CSS for Community Projects',
    description: 'Learn foundational web development concepts to build landing pages for local small businesses and NGOs.',
    type: 'YOUTUBE',
    url: 'https://www.youtube.com/watch?v=pQN-pnXPaVg',
    youtubeVideoId: 'pQN-pnXPaVg',
    thumbnailUrl: 'https://img.youtube.com/vi/pQN-pnXPaVg/hqdefault.jpg',
    category: 'Web Development',
    durationOrPages: '1 hr 15 mins',
    publishedBy: 'user-vp-growth',
    publisherName: 'Babatunde Adeleke',
    publisherRole: 'VP_GROWTH',
    createdAt: '2026-09-25T16:00:00Z',
  },
];

export const INITIAL_REPORTS: MonthlyReport[] = [
  {
    id: 'rep-1',
    month: 'September 2026',
    year: 2026,
    monthIndex: 8,
    submitterId: 'user-lg-pres',
    submitterName: 'Olumide Williams',
    submitterRole: 'LG_PRESIDENT',
    lgId: 'lg-akure',
    lgName: 'Akure South LG',
    state: 'Ondo State',
    activitiesAssigned: 4,
    activitiesCompleted: 4,
    evidence: 'https://drive.google.com/drive/folders/dodeel-ikeja-sept-2026',
    results: 'Reached 64 students at Agidingbi Grammar School; conducted 4 weekly peer mentoring sessions; verified 42 active CDS members.',
    beneficiariesReached: 64,
    challenges: 'Lack of enough functioning computer monitors at the school computer lab; students had to share screens in pairs.',
    outstandingTasks: 'Finalize logistics for market artisan mobile banking training in October.',
    nextMonthPlan: 'Mobilize 50 local market traders for digital accounting app training; launch inter-school tech quiz.',
    submittedAt: '2026-09-30T16:45:00Z',
    status: 'REVIEWED',
  },
  {
    id: 'rep-2',
    month: 'September 2026',
    year: 2026,
    monthIndex: 8,
    submitterId: 'user-vp-growth',
    submitterName: 'Babatunde Adeleke',
    submitterRole: 'VP_GROWTH',
    lgId: 'lg-akure',
    lgName: 'State Secretariat',
    state: 'Ondo State',
    activitiesAssigned: 3,
    activitiesCompleted: 3,
    evidence: 'https://instagram.com/dodeel_lagos (Verified campaign posts & analytics screenshots)',
    results: 'Acquired 38 new registered members; Instagram followers grew by 450; 3 new YouTube learning tutorials published.',
    beneficiariesReached: 38,
    challenges: 'Delays in acquiring branded t-shirts for executive visibility team.',
    outstandingTasks: 'Follow up with inactive members in Badagry and Epe zones.',
    nextMonthPlan: 'Host DO-DEEL state-wide AI webinar; roll out member referral rewards badge.',
    submittedAt: '2026-09-30T18:20:00Z',
    status: 'REVIEWED',
  },
];
