import {
  Activity,
  CDSDocument,
  LearningResource,
  LocalGovernment,
  Member,
  MonthlyReport,
  Task,
} from '../types';

export const INITIAL_LGS: LocalGovernment[] = [
  {
    id: 'lg-akoko-ne',
    name: 'Akoko North-East LG (Ikare)',
    state: 'Ondo State',
    meetingVenue: 'Ikare Local Government Secretariat Hall, Ikare-Akoko',
    meetingDay: 'Every Thursday, 10:00 AM',
    activeMemberCount: 0,
  },
  {
    id: 'lg-akoko-nw',
    name: 'Akoko North-West LG (Okeagbe)',
    state: 'Ondo State',
    meetingVenue: 'Okeagbe Local Government Secretariat',
    meetingDay: 'Every Thursday, 10:00 AM',
    activeMemberCount: 0,
  },
  {
    id: 'lg-akoko-se',
    name: 'Akoko South-East LG (Isua)',
    state: 'Ondo State',
    meetingVenue: 'Isua Local Government Secretariat Complex',
    meetingDay: 'Every Thursday, 10:00 AM',
    activeMemberCount: 0,
  },
  {
    id: 'lg-akoko-sw',
    name: 'Akoko South-West LG (Oka)',
    state: 'Ondo State',
    meetingVenue: 'Oka Local Government Hall, Oka-Akoko',
    meetingDay: 'Every Thursday, 10:00 AM',
    activeMemberCount: 0,
  },
  {
    id: 'lg-akure-north',
    name: 'Akure North LG (Iju/Itaogbolu)',
    state: 'Ondo State',
    meetingVenue: 'Akure North Local Government Secretariat, Iju',
    meetingDay: 'Every Thursday, 10:00 AM',
    activeMemberCount: 0,
  },
  {
    id: 'lg-akure',
    name: 'Akure South LG (Akure)',
    state: 'Ondo State',
    meetingVenue: 'Akure South Local Government Hall, Akure',
    meetingDay: 'Every Thursday, 10:00 AM',
    activeMemberCount: 0,
  },
  {
    id: 'lg-ese-odo',
    name: 'Ese Odo LG (Igbekebo)',
    state: 'Ondo State',
    meetingVenue: 'Ese Odo Secretariat Hall, Igbekebo',
    meetingDay: 'Every Thursday, 10:00 AM',
    activeMemberCount: 0,
  },
  {
    id: 'lg-idanre',
    name: 'Idanre LG (Owena/Idanre)',
    state: 'Ondo State',
    meetingVenue: 'Idanre Local Government Secretariat, Owena',
    meetingDay: 'Every Thursday, 10:00 AM',
    activeMemberCount: 0,
  },
  {
    id: 'lg-ifedore',
    name: 'Ifedore LG (Igbara-Oke)',
    state: 'Ondo State',
    meetingVenue: 'Ifedore Local Government Secretariat, Igbara-Oke',
    meetingDay: 'Every Thursday, 10:00 AM',
    activeMemberCount: 0,
  },
  {
    id: 'lg-ilaje',
    name: 'Ilaje LG (Igbokoda)',
    state: 'Ondo State',
    meetingVenue: 'Ilaje Local Government Secretariat, Igbokoda',
    meetingDay: 'Every Thursday, 10:00 AM',
    activeMemberCount: 0,
  },
  {
    id: 'lg-ile-oluji',
    name: 'Ile-Oluji/Okeigbo LG (Ile-Oluji)',
    state: 'Ondo State',
    meetingVenue: 'Ile-Oluji Local Government Hall, Ile-Oluji',
    meetingDay: 'Every Thursday, 10:00 AM',
    activeMemberCount: 0,
  },
  {
    id: 'lg-irele',
    name: 'Irele LG (Ode Irele)',
    state: 'Ondo State',
    meetingVenue: 'Irele Local Government Secretariat, Ode-Irele',
    meetingDay: 'Every Thursday, 10:00 AM',
    activeMemberCount: 0,
  },
  {
    id: 'lg-odigbo',
    name: 'Odigbo LG (Ore)',
    state: 'Ondo State',
    meetingVenue: 'Odigbo Secretariat Complex, Ore',
    meetingDay: 'Every Thursday, 9:30 AM',
    activeMemberCount: 0,
  },
  {
    id: 'lg-okitipupa',
    name: 'Okitipupa LG (Okitipupa)',
    state: 'Ondo State',
    meetingVenue: 'Okitipupa Local Government Hall, Okitipupa',
    meetingDay: 'Every Thursday, 10:00 AM',
    activeMemberCount: 0,
  },
  {
    id: 'lg-ondo-east',
    name: 'Ondo East LG (Bolorunduro)',
    state: 'Ondo State',
    meetingVenue: 'Ondo East Local Government Secretariat, Bolorunduro',
    meetingDay: 'Every Thursday, 10:00 AM',
    activeMemberCount: 0,
  },
  {
    id: 'lg-ondo-west',
    name: 'Ondo West LG (Ondo City)',
    state: 'Ondo State',
    meetingVenue: 'Ondo West Youth Centre, Ondo City',
    meetingDay: 'Every Thursday, 10:00 AM',
    activeMemberCount: 0,
  },
  {
    id: 'lg-ose',
    name: 'Ose LG (Ifon)',
    state: 'Ondo State',
    meetingVenue: 'Ose Local Government Secretariat, Ifon',
    meetingDay: 'Every Thursday, 10:00 AM',
    activeMemberCount: 0,
  },
  {
    id: 'lg-owo',
    name: 'Owo LG (Owo)',
    state: 'Ondo State',
    meetingVenue: 'Owo Local Government Secretariat, Owo',
    meetingDay: 'Every Thursday, 11:00 AM',
    activeMemberCount: 0,
  },
];

export const INITIAL_MEMBERS: Member[] = [
  {
    id: 'user-kolawole',
    fullName: 'Kolawole (Super Admin)',
    email: 'kolawoles445@gmail.com',
    phone: '+234 800 000 0001',
    lgId: 'lg-akure',
    lgName: 'Akure South LG (Akure)',
    state: 'Ondo State',
    role: 'CDS_COORDINATOR',
    membershipStatus: 'ACTIVE',
    accountStatus: 'ACTIVE',
    dateJoined: '2026-10-01',
    skills: ['System Administration', 'Strategic Governance', 'Directorate Oversight'],
    bio: 'Super Administrator & State CDS Coordinator with complete system oversight and executive authority.',
    assignedTeam: 'State Directorate',
  },
  {
    id: 'user-joma',
    fullName: 'Joma Schools Admin',
    email: 'jomaschools@gmail.com',
    phone: '+234 800 000 0000',
    lgId: 'lg-akure',
    lgName: 'Akure South LG (Akure)',
    state: 'Ondo State',
    role: 'CDS_COORDINATOR',
    membershipStatus: 'ACTIVE',
    accountStatus: 'ACTIVE',
    dateJoined: '2026-10-01',
    skills: ['System Administration', 'Education Management'],
    bio: 'Primary Administrator for DO-DEEL CDS Manager.',
    assignedTeam: 'Management',
  },
];

export const INITIAL_TASKS: Task[] = [];
export const INITIAL_ACTIVITIES: Activity[] = [];
export const INITIAL_DOCUMENTS: CDSDocument[] = [];
export const INITIAL_LEARNING: LearningResource[] = [];
export const INITIAL_REPORTS: MonthlyReport[] = [];
